### ISSUE TITLE
Unfortunately, not working with updated dependencies

### ISSUE THREAD

**Issue by alexsintoni** [raoshahid799/ng-full-calendar-ngx-popover#1]
Dear @raoshahid799 ,

first of all, thanks a million for your example.

I would like to take your solution to show tooltips of the event in my project, but unfortunately, this solution do not work with last version of dependencies.
I have also downloaded whit repository and updated the dependencies with `npm update` and the popover are not shown anymore.

Do you think you have the time to check it out and update the example with new versions of the dependencies?

In any case, thanks a million to create it :)

**Comment by raoshahid799** [comment]
hi you are welcome :)  after update can you confirm, updated version of following libraries  . i will try look into this  issue. 
tether library used to position popover , ngx bootstrap mostly changes event name in new versions, you have to verify output event name. might be are changed  
   "ng-fullcalendar": "1.7.1",
    "ngx-bootstrap": "^3.1.4",
    "tether": "^1.4.5",

**Comment by alexsintoni** [comment]
Dear @raoshahid799 

thanks a million for your reply.
Please, here `package.json` after I have run `npm update`:
```
{
  "name": "ng-full-calendar-ngx-popover",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^7.2.16",
    "@angular/common": "^7.2.16",
    "@angular/compiler": "^7.2.16",
    "@angular/core": "^7.2.16",
    "@angular/forms": "^7.2.16",
    "@angular/platform-browser": "^7.2.16",
    "@angular/platform-browser-dynamic": "^7.2.16",
    "@angular/router": "^7.2.16",
    "bootstrap": "^4.2.1",
    "core-js": "^2.6.11",
    "fullcalendar": "3.10.0",
    "jquery": "^3.4.1",
    "moment": "^2.18.0",
    "ng-fullcalendar": "1.7.1",
    "ngx-bootstrap": "^3.1.4",
    "rxjs": "^6.5.4",
    "rxjs-compat": "^6.5.4",
    "tether": "^1.4.7",
    "tslib": "^1.10.0",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.12.0",
    "@angular/cli": "~7.2.1",
    "@angular/compiler-cli": "^7.2.16",
    "@angular/language-service": "^7.2.16",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "^2.0.8",
    "@types/jquery": "^3.3.31",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.5.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.1.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^2.0.6",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~3.2.2"
  }
}
```

**Comment by raoshahid799** [comment]
Simple solution for this. 
Remove ^ sign from ngx and tether library 
delete node_module folder 
run npm install 
it will work 
now on it will not create issue upon npm update command 
^ sign update the ngx and tether libraries into latest update of 3.x.x 
sometime ^ create issue

**Comment by alexsintoni** [comment]
Hi @raoshahid799 

it  is working now ;)
I am using the same dependencies versions in my project as well and it works ;)

I close the ticket then.

Just for curiosity, do you think you will try to make it work also with last version of all the dependencies?

**Comment by raoshahid799** [comment]
when i was working on a project. i did not find solution so i created this.  i thought i can help others. i  posted here. i got chance to work on it . i will

**Comment by alexsintoni** [comment]
@raoshahid799 indeed your example helped me and I am currently using your solution ;)
I will keep checking it and if you have the time to update it, I will use the new solution with updated dependencies.
In any case, thanks a million :)
